# Generated by Django 2.2.7 on 2019-11-24 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='fMenu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Menu'),
        ),
    ]
