# Generated by Django 2.2.7 on 2019-11-24 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191124_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='lurl',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='menu',
            name='fMenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Menu'),
        ),
    ]
